import data from "./content.generated.json";

/* Types describing the editorial data exported from the original prototype.
   The copy itself lives in content.generated.json and is regenerated by
   `node tools/export-content.mjs`, so it is never retyped by hand. */

export type Track = {
  name: string;
  difficulty: string;
  terrain: string;
  sighting: string;
  blurb: string;
};

/** [photoSlug, name, caption, href?] - a dive or snorkelling site shown as a photo card. */
export type Site = [string, string, string] | [string, string, string, string];

export type Section = {
  h: string;
  p?: string[];
  cards?: [string, string][];
  list?: [string, string][];
  links?: [string, string][];
  sites?: Site[];
  tracks?: Track[];
  trackNote?: string;
  note?: string;
};

/** The brief specifies a different gallery layout per destination. */
export type GalleryLayout = "grid" | "masonry" | "rail" | "mosaic" | "wide";

export type Gallery = { label: string; items: [string, string][]; layout?: GalleryLayout };

export type Article = {
  nav: string;
  crumb: [string, string];
  title: string;
  h1: string;
  eyebrow?: string;
  tagline: string;
  lede: string[];
  sections: Section[];
  facts?: [string, string][];
  chips?: string[];
  gallery?: Gallery;
  quotes?: { label: string; note?: string; items: [string, string, string][] };
  close?: string;
  cta: { line: string; label: string; href: string };
};

export type Vessel = {
  name: string;
  state: "active" | "retired" | "soon";
  ship_id: string | null;
  tagline: string;
  intro: string;
};

export type Room = {
  key: string;
  name: string;
  category: string;
  desc: string;
  units: number;
  location: string;
  occupancy: string;
  amenities: string;
};

export type Testimonial = {
  name: string;
  country: string;
  rating: number;
  date: string;
  lang?: string;
  source?: string;
  body: string;
};

type Raw = {
  experiences: Record<string, Article>;
  destinations: Record<string, Article>;
  vessels: Record<string, Vessel>;
  rooms: Room[];
  specs: [string, string | null, boolean?][];
  crew: [string, string, string][];
  testimonials: Testimonial[];
  destinationOrder: [string, string][];
  experienceOrder: [string, string][];
  contact: {
    phone: string;
    email: string;
    address: string;
    instagram: string;
    youtube: string;
    pending: boolean;
  };
  languages: [string, string][];
};

const raw = data as unknown as Raw;

export const EXPERIENCES = raw.experiences;
export const DESTINATIONS = raw.destinations;
export const VESSELS = raw.vessels;
export const ROOMS = raw.rooms;
export const SPECS = raw.specs;
export const CREW = raw.crew;
export const TESTIMONIALS = raw.testimonials;

/**
 * The reviews shown on the English site.
 *
 * These are real, attributed guest reviews, so the ones written in another language are filtered
 * out rather than translated: putting English words next to a named person's byline would be
 * putting words in their mouth. They stay in the content file for the day the translated sites
 * are published, where each one belongs with its own locale.
 */
export const ENGLISH_TESTIMONIALS = raw.testimonials.filter(
  (t: { lang?: string }) => !t.lang || t.lang.startsWith("en"),
);
export const DESTINATION_ORDER = raw.destinationOrder;
export const EXPERIENCE_ORDER = raw.experienceOrder;
export const CONTACT = raw.contact;
export const LANGUAGES = raw.languages;

export const experienceSlugs = Object.keys(EXPERIENCES);
export const destinationSlugs = Object.keys(DESTINATIONS);
export const vesselSlugs = Object.keys(VESSELS);

export function getExperience(slug: string): Article | undefined {
  return EXPERIENCES[slug];
}
export function getDestination(slug: string): Article | undefined {
  return DESTINATIONS[slug];
}
export function getVessel(slug: string): Vessel | undefined {
  return VESSELS[slug];
}

/** The editorial copy carries a few inline links and entities, e.g. "Paddling &amp; kayaking". */
export function decode(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"');
}

/** Strip any inline markup, for places that need plain text (title tags, alt text). */
export function plain(s: string): string {
  return decode(s.replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim();
}
